# -*- coding: utf-8 -*-
"""FYProject-II: VideoQA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19gVfdowvvY5NPMoUEsRVz8KG4dFjzkqv
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install git+https://github.com/DAMO-NLP-SG/VideoLLaMA2.git --no-deps
!pip install git+https://github.com/openai/CLIP.git
!pip install decord
!pip install --upgrade pip torch torch_xla flash-attn --no-build-isolation

import os
import torch
import clip
import cv2
import numpy as np
from tqdm import tqdm
from PIL import Image
import subprocess
import csv
from collections import Counter
import warnings
from videollama2 import model_init, mm_infer
from videollama2.utils import disable_torch_init

# Suppress unnecessary warnings from transformers
warnings.filterwarnings("ignore", category=UserWarning, module="transformers")

os.environ["USE_FLASH_ATTENTION_2"] = "1"
os.environ["DISABLE_FLASH_ATTN"] = "0"
os.environ["HF_ATTENTION_IMPLEMENTATION"] = "flash_attention_2"
os.environ["TRANSFORMERS_NO_ADVISORY_WARNINGS"] = "1"

device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

clip_model, preprocess = clip.load("ViT-B/32", device=device)
clip_model = clip_model.float()  # Converting to FP32 for stability
print("CLIP model loaded.")

def extract_frames(video_path, frame_rate=1):
    cap = cv2.VideoCapture(video_path)
    frames = []
    frame_count = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break
        if frame_count % int(cap.get(cv2.CAP_PROP_FPS) // frame_rate) == 0:
            frames.append(frame)
        frame_count += 1

    cap.release()
    return frames

def encode_frames(frames, model, preprocess, device):
    frame_tensors = [
        preprocess(Image.fromarray(cv2.cvtColor(f, cv2.COLOR_BGR2RGB))).unsqueeze(0)
        for f in frames
    ]
    frame_tensors = torch.cat(frame_tensors).to(device)

    with torch.no_grad():
        frame_features = model.encode_image(frame_tensors).float()
        frame_features = frame_features.to(torch.float32)  # Convert explicitly to FP32
        frame_features /= frame_features.norm(dim=-1, keepdim=True)

    return frame_features.mean(dim=0, keepdim=True)  # Aggregate by mean pooling

# Define paths for features and keyframe mappings
features_dir = "/content/drive/MyDrive/VQA_Dataset/clip-features-vit-b32-sample/clip-features"
map_dir = "/content/drive/MyDrive/VQA_Dataset/map-keyframes-sample/map-keyframes"

# Load features and keyframe mappings
features = {file.split('.')[0]: torch.from_numpy(np.load(os.path.join(features_dir, file))).float().to(device)
            for file in os.listdir(features_dir) if file.endswith('.npy')}
keyframe_mappings = {file.split('.')[0]: list(csv.DictReader(open(os.path.join(map_dir, file), 'r')))
                     for file in os.listdir(map_dir) if file.endswith('.csv')}

query = "Elephant in zoo"
print(f"Query: {query}")

# Encode text query
with torch.no_grad():
    text_features = clip_model.encode_text(clip.tokenize(query).to(device)).float()
    text_features /= text_features.norm(dim=-1, keepdim=True)
print("Query encoded")

# Compute similarity scores
results = []
for video_id, video_features in tqdm(features.items()):
    similarities = (100.0 * video_features @ text_features.T).squeeze()
    top_indices = similarities.argsort(descending=True)[:5]
    for idx in top_indices:
        score = similarities[idx].item()
        frame_info = keyframe_mappings[video_id][idx]
        results.append((video_id, idx, frame_info['frame_idx'], frame_info['pts_time'], score))

# Sort results by similarity score
results.sort(key=lambda x: x[4], reverse=True)

# Extract top 10 results
print("Top 10 results:")
for video_id, _, frame_idx, pts_time, score in results[:10]:
    print(f"Video ID: {video_id}, Frame Index: {frame_idx}, PTS Time: {pts_time}, Score: {score:.2f}")

# Identify most common video ID in top results
most_common_video_id, _ = Counter([video_id for video_id, _, _, _, _ in results[:10]]).most_common(1)[0]
print(f"Most common video ID: {most_common_video_id}")

# Extract timestamps for video clipping
pts_times = [float(pts_time) for video_id, _, _, pts_time, _ in results[:10] if video_id == most_common_video_id]
min_pts_time, max_pts_time = min(pts_times) - 3, max(pts_times) + 3

# Define video paths
video_path = f'/content/drive/MyDrive/VQA_Dataset/video/{most_common_video_id}.mp4'
# Ensure video exists
if os.path.exists(video_path):
    print(f"Video found at: {video_path}")
else:
    print(f"Video NOT found at: {video_path}")

from transformers import BitsAndBytesConfig
from videollama2 import model_init
import torch
bnb_config = BitsAndBytesConfig(
    load_in_8bit=True,  # 8-bit quantization
    llm_int8_threshold=6.0
)

model_path = "DAMO-NLP-SG/VideoLLaMA2-7B"  # Set your model path here

model, processor, tokenizer = model_init(
    model_path,
    torch_dtype=torch.float16,
    device_map="auto"
)

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="transformers")
instruct = "What is the color shirt is the woman wearing in the news deck?"
output = mm_infer(processor["video"](video_path), instruct, model=model, tokenizer=tokenizer, do_sample=False, modal="video")

print("Generated Answer:")
print(output)